name: Build and publish Python wheels

on:
  push:
    tags:
      - 'v*'    # Publish only when you push a version tag, like v1.0.0
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          args: --release --sdist -o dist

      - name: Audit wheels (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install auditwheel
          auditwheel show dist/*.whl

      - name: Store wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: '**' # Download all artifacts

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: publish
          args: --skip-existing -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
